const DEFAULT_BACKEND="https://rolling-wrench-ai-backend.onrender.com";
const DEFAULT_SUPABASE="https://uxpkqwcmvtqvubibbrek.supabase.co";
const SUPABASE_KEY="eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InV4cGtxd2NtdnViaWJicm9sZSI6ImFub24iLCJpYXQiOjE3NzcyMzk4NjQsImV4cCI6MjA5MjgxNTg2NH0.afiaSFqkRFEXW5nPQVRXKZcpKkS6iF3T_hTQC2P15HQ";
const $=id=>document.getElementById(id);let historyStack=["home"],mode="shop",signatureData="";
const catalog={"4376357":{name:"Water Pump",engine:"Cummins ISX",group:"Cooling"},"4309129":{name:"NOx Sensor",engine:"Cummins ISX",group:"Emissions"},"4954200":{name:"Fuel Injector",engine:"Cummins ISX",group:"Fuel"},"A4722001601":{name:"Water Pump",engine:"Detroit DD15",group:"Cooling"},"2293961":{name:"NOx Sensor",engine:"PACCAR MX-13",group:"Emissions"},"1831541":{name:"Fan Clutch",engine:"PACCAR MX-13",group:"Cooling"},"3007353C92":{name:"Oil Cooler",engine:"International A26",group:"Cooling"}};
function safeText(v){return String(v??"").replace(/[&<>'"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","'":"&#39;","\"":"&quot;"}[c]))}
function money(n){return "$"+Number(n||0).toFixed(2)}
function showScreen(id){if(!$(id))return;document.querySelectorAll('.screen').forEach(s=>s.classList.remove('active'));$(id).classList.add('active');if(historyStack[historyStack.length-1]!==id)historyStack.push(id);$('drawer')?.classList.remove('open');window.scrollTo({top:0,behavior:'smooth'});if(id==='clocks')renderClocks();if(id==='finance')calcFinance();if(id==='customers')loadCustomers();}
function goBack(){historyStack.pop();const last=historyStack.pop()||'home';showScreen(last)}
function toggleMenu(){$('drawer').classList.toggle('open')}
function setMode(m){mode=m;$('shopBtn').classList.toggle('active',m==='shop');$('roadBtn').classList.toggle('active',m==='roadside');$('serviceToggle').checked=m==='roadside';$('invServiceToggle').checked=m==='roadside';buildQuote();}
function clearField(id){if($(id))$(id).value=""}
function help(topic){const tips={parts:'Enter VIN or part/job name. Use supplier buttons for real-world web searches. Add found prices to quote.',quote:'Fill customer, hours, parts and service call. Use Write Professional to clean wording, then Build Quote.',invoice:'Build invoice, have customer sign in the white box, then Text Invoice.',scan:'Upload receipt or part label. Scan photo, parse vendor/part/price, then add to quote.',clocks:'Three independent clocks. Start, pause/resume, stop, send any job time to invoice.',finance:'Tracks rough weekly revenue, bills, break-even hours, and take-home estimate.',settings:'Pick theme/layout and save. Test backend and Supabase here.'};alert(tips[topic]||'Rolling Wrench AI help. Use Back, Clear, Save, Send on every major screen.')}
function applyTheme(t){document.body.dataset.theme=t;localStorage.setItem('rw_theme',t)}
function applyLayout(l){document.body.dataset.layout=l;localStorage.setItem('rw_layout',l)}
function settings(){return JSON.parse(localStorage.getItem('rw_settings')||'{}')}
function saveSettings(){const s={shopName:$('shopName').value,shopPhone:$('shopPhone').value,shopWebsite:$('shopWebsite').value,rate:$('setRate').value,service:$('setService').value,markup:$('setMarkup').value,backend:$('backendUrl').value,supabase:$('supabaseUrl').value,theme:$('themeSelect').value,layout:$('layoutSelect').value};localStorage.setItem('rw_settings',JSON.stringify(s));applyTheme(s.theme);applyLayout(s.layout);$('settingsOut').textContent='Settings saved.';}
function loadSettings(){const s=settings();$('shopName').value=s.shopName||'Rolling Wrench Diesel LLC';$('shopPhone').value=s.shopPhone||'260-502-6222';$('shopWebsite').value=s.shopWebsite||'www.rollingwrenchdiesel.com';$('setRate').value=s.rate||135;$('setService').value=s.service||250;$('setMarkup').value=s.markup||15;$('backendUrl').value=s.backend||DEFAULT_BACKEND;$('supabaseUrl').value=s.supabase||DEFAULT_SUPABASE;$('themeSelect').value=s.theme||localStorage.getItem('rw_theme')||'inferno';$('layoutSelect').value=s.layout||localStorage.getItem('rw_layout')||'command';applyTheme($('themeSelect').value);applyLayout($('layoutSelect').value);$('quoteRate').value=s.rate||135;$('invRate').value=s.rate||135;$('serviceAmount').value=s.service||250;$('invService').value=s.service||250;$('quoteMarkup').value=s.markup||15;}
async function apiCall(path,payload){const base=(settings().backend||DEFAULT_BACKEND).replace(/\/$/,'');const urls=[base+path,base+'/api'+path,base];for(const url of urls){try{const r=await fetch(url,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)});if(r.ok)return await r.json();}catch(e){}}throw new Error('Backend did not answer this request yet. Using local fallback.');}
async function askAI(){const q=$('aiQuestion').value.trim();if(!q)return alert('Ask a question first.');$('aiOut').textContent='Rolling Wrench AI thinking...';try{const data=await apiCall('/ai',{question:q,vehicleContext:ctx()});$('aiOut').textContent=data.answer||data.message||JSON.stringify(data,null,2)}catch(e){$('aiOut').textContent='Local fallback: '+professionalText(q)+'\n\nBackend note: '+e.message}}
function professionalText(text){return `Customer concern / request:\n${text}\n\nProfessional note:\nInspection and diagnostic steps will be performed to verify the root cause before replacement of parts. Any additional repairs, parts, or labor discovered during service will be communicated for approval before proceeding.`}
function writeProfessional(id){const el=$(id);if(!el)return;el.value=professionalText(el.value||'Service request')}
function ctx(){return `VIN:${$('vin')?.value||$('invVin')?.value||''} Unit:${$('quoteTruck')?.value||$('invTruck')?.value||''} Mode:${mode}`}
async function decodeVin(){const vin=$('vin').value.trim().toUpperCase();if(!vin)return alert('Enter VIN first.');$('vinOut').textContent='Decoding VIN...';try{const r=await fetch('https://vpic.nhtsa.dot.gov/api/vehicles/DecodeVinValuesExtended/'+encodeURIComponent(vin)+'?format=json');const d=(await r.json()).Results?.[0]||{};const txt=`VIN: ${vin}\nYear: ${d.ModelYear||'Not returned'}\nMake: ${d.Make||'Not returned'}\nModel: ${d.Model||'Not returned'}\nEngine: ${d.EngineModel||d.EngineConfiguration||'Not returned'}\nNote: Heavy truck engine/trans may need manual verification.`;$('vinOut').textContent=txt;$('quoteTruck').value=[d.ModelYear,d.Make,d.Model].filter(Boolean).join(' ');$('invTruck').value=$('quoteTruck').value;$('invVin').value=vin;localStorage.setItem('rw_active_truck',JSON.stringify({vin,truck:$('quoteTruck').value}));updateMini();}catch(e){$('vinOut').textContent='VIN decode failed. '+e.message}}
function saveTruck(){const t={vin:$('vin').value,truck:$('quoteTruck').value||$('invTruck').value,date:new Date().toLocaleString()};localStorage.setItem('rw_active_truck',JSON.stringify(t));updateMini();alert('Truck saved.')}
function updateMini(){const t=JSON.parse(localStorage.getItem('rw_active_truck')||'{}');$('activeUnitMini').textContent=t.truck||t.vin||'No unit saved'}
function clearParts(){['vin','partQ'].forEach(clearField);$('vinOut').textContent='VIN decoder ready.';$('partOut').textContent='Part results appear here.'}
async function lookupPart(){const q=$('partQ').value.trim();if(!q)return alert('Enter a part or job.');$('partOut').textContent='Searching parts...';let local=[];for(const [num,p] of Object.entries(catalog)){const hay=(num+' '+p.name+' '+p.engine+' '+p.group).toLowerCase();if(hay.includes(q.toLowerCase())||q.toLowerCase().split(' ').some(w=>w.length>2&&hay.includes(w)))local.push(`${num} — ${p.name} (${p.engine}) ${p.group}`)}try{const data=await apiCall('/parts',{query:q,vehicleContext:ctx()});$('partOut').textContent=(data.answer||data.message||JSON.stringify(data,null,2))+'\n\nLOCAL CATALOG:\n'+(local.join('\n')||'No local match.')}catch(e){$('partOut').textContent='LOCAL CATALOG:\n'+(local.join('\n')||'No local match.')+'\n\nSUPPLIER NEXT STEP: use buttons below.\nBackend: '+e.message}}
function supplierSearch(s){const q=encodeURIComponent($('partQ').value||$('scanPart').value||'diesel truck parts');const urls={fleetpride:`https://www.google.com/search?q=site%3Afleetpride.com+${q}`,truckpro:`https://www.google.com/search?q=site%3Atruckpro.com+${q}`,napa:`https://www.napaonline.com/en/search?text=${q}`,oreilly:`https://www.oreillyauto.com/search?q=${q}`,cummins:`https://www.google.com/search?q=Cummins+QuickServe+${q}`,google:`https://www.google.com/search?q=${q}+heavy+duty+truck+part`};window.open(urls[s]||urls.google,'_blank')}
function addPartToQuote(){const text=$('partOut').innerText||$('partQ').value;$('quoteDesc').value=($('quoteDesc').value+'\nParts/lookup: '+text).trim();showScreen('quote')}
function totals(prefix){const h=Number($(prefix+'Hours').value||0),r=Number($(prefix+'Rate').value||0),parts=Number($(prefix+'Parts').value||0),markup=Number($('quoteMarkup')?.value||0),svcOn=$(prefix==='quote'?'serviceToggle':'invServiceToggle').checked,svc=svcOn?Number($(prefix==='quote'?'serviceAmount':'invService').value||0):0,taxPct=Number($(prefix==='quote'?'taxRate':'invTax').value||0),cardPct=Number($('cardFee')?.value||0);const labor=h*r,partsSell=prefix==='quote'?parts*(1+markup/100):parts,sub=labor+partsSell+svc,tax=sub*(taxPct/100),card=(sub+tax)*(cardPct/100),total=sub+tax+card;return{h,r,labor,parts,partsSell,svc,tax,card,total,sub}}
function shopInfo(){const s=settings();return{sname:s.shopName||'Rolling Wrench Diesel LLC',phone:s.shopPhone||'260-502-6222',web:s.shopWebsite||'www.rollingwrenchdiesel.com'}}
function docHTML(type,customer,phone,truck,vin,desc,t,signature=false){const s=shopInfo();return `<div class="docHeader"><div><b>${safeText(s.sname)}</b><br>${safeText(s.phone)}<br>${safeText(s.web)}</div><div><b>${type}</b><br>${new Date().toLocaleString()}<br>Mode: ${mode.toUpperCase()}</div></div><b>Customer:</b> ${safeText(customer||'')}<br><b>Phone:</b> ${safeText(phone||'')}<br><b>Vehicle:</b> ${safeText(truck||'')}<br><b>VIN:</b> ${safeText(vin||'')}<br><br><b>Work Description:</b><br>${safeText(desc||'')}<br><br>Labor (${t.h} hrs @ ${money(t.r)}): ${money(t.labor)}<br>Parts: ${money(t.partsSell)}<br>Service Call: ${money(t.svc)}<br>Tax: ${money(t.tax)}<br>${t.card?`Card Fee: ${money(t.card)}<br>`:''}<div class="docTotal">TOTAL: ${money(t.total)}</div><br><b>Terms:</b> Price may vary if additional parts, labor, diagnostics, or hidden damage are discovered. Work must be approved before additional repairs are completed.<br>${signature&&signatureData?`<br><b>Customer Signature:</b><br><img src="${signatureData}" style="max-width:360px;border:1px solid #333;border-radius:8px;background:white">`:''}`}
function buildQuote(){const t=totals('quote');$('quoteOut').innerHTML=docHTML('QUOTE',$('quoteCustomer').value,$('quotePhone').value,$('quoteTruck').value,$('vin').value,$('quoteDesc').value,t);$('todayRevenue').textContent=money(t.total);return t}
function clearQuote(){['quoteCustomer','quotePhone','quoteTruck','quoteDesc'].forEach(clearField);$('quoteHours').value=1;$('quoteParts').value=0;$('quoteOut').textContent='Quote preview appears here.'}
function sendQuoteText(){buildQuote();const body=encodeURIComponent($('quoteOut').innerText);location.href=`sms:${$('quotePhone').value||''}&body=${body}`}
function copyFromQuote(){$('invCustomer').value=$('quoteCustomer').value;$('invPhone').value=$('quotePhone').value;$('invTruck').value=$('quoteTruck').value;$('invHours').value=$('quoteHours').value;$('invRate').value=$('quoteRate').value;$('invParts').value=totals('quote').partsSell.toFixed(2);$('invDesc').value=$('quoteDesc').value}
function buildInvoice(){const t=totals('inv');$('invoiceOut').innerHTML=docHTML('INVOICE',$('invCustomer').value,$('invPhone').value,$('invTruck').value,$('invVin').value,$('invDesc').value,t,true);saveInvoiceLocal(t);return t}
function clearInvoice(){['invCustomer','invPhone','invTruck','invVin','invDesc'].forEach(clearField);$('invHours').value=1;$('invParts').value=0;$('invoiceOut').textContent='Invoice preview appears here.';clearSignature()}
function sendInvoiceText(){buildInvoice();const body=encodeURIComponent($('invoiceOut').innerText);location.href=`sms:${$('invPhone').value||''}&body=${body}`}
function saveInvoiceLocal(t){const list=JSON.parse(localStorage.getItem('rw_invoices')||'[]');list.unshift({date:new Date().toISOString(),customer:$('invCustomer').value,total:t.total});localStorage.setItem('rw_invoices',JSON.stringify(list.slice(0,200)))}
let sigPad={drawing:false,ctx:null};function setupSignature(){const c=$('sigCanvas');if(!c)return;sigPad.ctx=c.getContext('2d');sigPad.ctx.lineWidth=4;sigPad.ctx.lineCap='round';sigPad.ctx.strokeStyle='#111';const pos=e=>{const r=c.getBoundingClientRect();const p=e.touches?e.touches[0]:e;return{x:(p.clientX-r.left)*(c.width/r.width),y:(p.clientY-r.top)*(c.height/r.height)}};const down=e=>{sigPad.drawing=true;const p=pos(e);sigPad.ctx.beginPath();sigPad.ctx.moveTo(p.x,p.y);e.preventDefault()};const move=e=>{if(!sigPad.drawing)return;const p=pos(e);sigPad.ctx.lineTo(p.x,p.y);sigPad.ctx.stroke();e.preventDefault()};const up=()=>{sigPad.drawing=false};c.addEventListener('mousedown',down);c.addEventListener('mousemove',move);window.addEventListener('mouseup',up);c.addEventListener('touchstart',down,{passive:false});c.addEventListener('touchmove',move,{passive:false});c.addEventListener('touchend',up)}
function clearSignature(){const c=$('sigCanvas');if(c){sigPad.ctx=c.getContext('2d');sigPad.ctx.clearRect(0,0,c.width,c.height)}signatureData='';$('sigStatus').textContent='No signature saved.'}
function saveSignature(){const c=$('sigCanvas');signatureData=c.toDataURL('image/png');$('sigStatus').textContent='Signature saved and will appear on invoice.';buildInvoice()}
function previewScan(e){const f=e.target.files?.[0];if(!f)return;const url=URL.createObjectURL(f);$('scanPreview').src=url;$('scanPreview').style.display='block';$('scanOut').textContent='Photo loaded. Tap SCAN PHOTO.'}
async function runOCR(){const f=$('scanFile').files?.[0];if(!f)return alert('Add a photo first.');$('scanOut').textContent='Reading photo...';try{if(!window.Tesseract)throw new Error('Tesseract not loaded');const r=await Tesseract.recognize(f,'eng');$('scanText').value=r.data.text||'';$('scanOut').textContent='OCR complete. Tap PULL PART + PRICE.'}catch(e){$('scanOut').textContent='OCR failed: '+e.message}}
function parseReceipt(){const txt=$('scanText').value.toUpperCase();const vendor=(txt.match(/FLEETPRIDE|NAPA|O.?REILLY|TRUCKPRO|CUMMINS|PETERBILT|KENWORTH|FREIGHTLINER/)||[''])[0];const part=(txt.match(/\b[A-Z]{0,3}\d{4,8}[A-Z0-9-]*\b/)||[''])[0];const prices=[...txt.matchAll(/\$?\s*(\d{1,4}\.\d{2})/g)].map(m=>Number(m[1])).filter(n=>n>0);$('scanVendor').value=vendor;$('scanPart').value=part;$('scanPrice').value=prices.length?Math.max(...prices).toFixed(2):0;$('scanOut').textContent=`Parsed vendor: ${vendor||'unknown'}\nPart: ${part||'unknown'}\nPrice: ${$('scanPrice').value}`}
function addScanToQuote(){parseReceipt();const price=Number($('scanPrice').value||0)*Number($('scanQty').value||1);$('quoteParts').value=(Number($('quoteParts').value||0)+price).toFixed(2);$('quoteDesc').value=($('quoteDesc').value+`\nScanned part: ${$('scanPart').value} from ${$('scanVendor').value} Qty ${$('scanQty').value} Cost ${money(price)}`).trim();showScreen('quote');buildQuote()}
function clearScan(){['scanVendor','scanPart','scanText','scanOut'].forEach(id=>{if($(id))$(id).value?$(id).value='':$(id).textContent=''});$('scanQty').value=1;$('scanPrice').value=0;$('scanPreview').style.display='none'}
const defaultClocks=[{name:'Job A',elapsed:0,running:false,start:0},{name:'Job B',elapsed:0,running:false,start:0},{name:'Job C',elapsed:0,running:false,start:0}];function getClocks(){return JSON.parse(localStorage.getItem('rw_clocks')||JSON.stringify(defaultClocks))}function setClocks(c){localStorage.setItem('rw_clocks',JSON.stringify(c));renderClocks()}function clockHours(c){return (c.elapsed+(c.running?(Date.now()-c.start):0))/36e5}function startClock(i){const c=getClocks();if(!c[i].running){c[i].running=true;c[i].start=Date.now()}setClocks(c)}function pauseClock(i){const c=getClocks();if(c[i].running){c[i].elapsed+=Date.now()-c[i].start;c[i].running=false}setClocks(c)}function stopClock(i){pauseClock(i)}function resetClock(i){const c=getClocks();c[i].elapsed=0;c[i].running=false;c[i].start=0;setClocks(c)}function resetAllClocks(){if(confirm('Reset all clocks?'))setClocks(defaultClocks)}function sendClock(i){const h=clockHours(getClocks()[i]);$('invHours').value=h.toFixed(2);showScreen('invoice')}function renderClocks(){const c=getClocks();$('clockDeck').innerHTML=c.map((x,i)=>`<div class="clockCard glass"><h3>${x.name}</h3><input value="${x.name}" onchange="renameClock(${i},this.value)"><div class="clockTime">${clockHours(x).toFixed(2)} hrs</div><div class="buttonRow"><button onclick="startClock(${i})">START</button><button onclick="pauseClock(${i})">PAUSE</button><button onclick="startClock(${i})">RESUME</button><button onclick="stopClock(${i})">STOP</button><button onclick="sendClock(${i})">SEND TO INVOICE</button><button onclick="resetClock(${i})">RESET</button></div></div>`).join('')}function renameClock(i,v){const c=getClocks();c[i].name=v;localStorage.setItem('rw_clocks',JSON.stringify(c))}
function calcFinance(){const rent=Number($('rent').value||0),ins=Number($('insurance').value||0),el=Number($('electric').value||0),other=Number($('otherExp').value||0),h=Number($('weekHours').value||0),rate=Number($('financeRate').value||0),pp=Number($('partsProfit').value||0);const expenses=rent+ins+el+other,weekly=h*rate+pp,monthly=weekly*4.33,profit=monthly-expenses,breakEven=expenses/rate;$('financeOut').innerHTML=[['Weekly Revenue',weekly],['Monthly Revenue',monthly],['Monthly Expenses',expenses],['Est. Take Home',profit],['Break-even Hours',breakEven]].map(([k,v])=>`<div class="financeCard"><b>${k.includes('Hours')?Number(v).toFixed(1):money(v)}</b><span>${k}</span></div>`).join('')}
function saveCustomer(){const list=JSON.parse(localStorage.getItem('rw_customers')||'[]');list.unshift({name:$('custName').value,phone:$('custPhone').value,truck:$('custTruck').value,vin:$('custVin').value,notes:$('custNotes').value,date:new Date().toLocaleString()});localStorage.setItem('rw_customers',JSON.stringify(list.slice(0,200)));loadCustomers()}function loadCustomers(){const list=JSON.parse(localStorage.getItem('rw_customers')||'[]');$('customersOut').innerHTML=list.length?list.map(c=>`<div class="output small"><b>${safeText(c.name)}</b> ${safeText(c.phone)}<br>${safeText(c.truck)} VIN:${safeText(c.vin)}<br>${safeText(c.notes)}</div>`).join(''):'Saved customers show here.'}function clearCustomerForm(){['custName','custPhone','custTruck','custVin','custNotes'].forEach(clearField)}
async function testBackend(){try{const r=await fetch((settings().backend||DEFAULT_BACKEND)+'/health');$('settingsOut').textContent='Backend reachable: '+r.status}catch(e){$('settingsOut').textContent='Backend test failed: '+e.message}}async function testSupabase(){try{const u=settings().supabase||DEFAULT_SUPABASE;const r=await fetch(u+'/rest/v1/',{headers:{apikey:SUPABASE_KEY,Authorization:'Bearer '+SUPABASE_KEY}});$('settingsOut').textContent='Supabase reachable: '+r.status}catch(e){$('settingsOut').textContent='Supabase test failed: '+e.message}}
if('serviceWorker'in navigator){window.addEventListener('load',()=>navigator.serviceWorker.register('./service-worker.js').catch(()=>{}))}
window.addEventListener('DOMContentLoaded',()=>{loadSettings();updateMini();setupSignature();renderClocks();setInterval(()=>{if($('clocks')?.classList.contains('active'))renderClocks()},30000);buildQuote();calcFinance()});
